hydra:
  run:
    dir: ${env:PROJECT_PATH}/mtfsm_outputs/finetune/${hydra:runtime.choices.model}/${hydra:runtime.choices.data}/${run_name}
defaults:
  - model: moirai_1.0_R_small_ours_save
  - data: combine_all_split_prune_cov_merge_full
  - val_data: null
  - _self_
run_name: debug_run_finetune
seed: 0
tf32: true
compile: false
ckpt_path: null
trainer:
  _target_: lightning.Trainer
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  logger:
      _target_: lightning.pytorch.loggers.TensorBoardLogger
      save_dir: ${hydra:runtime.output_dir}
      name: logs
  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: epoch
    - _target_: uni2ts.callbacks.InitialCheckpoint.InitialCheckpointCallback
      model_tag: moirai_1.0_R_small_saved
  max_epochs: 0
  enable_progress_bar: true
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
train_dataloader:
  _target_: uni2ts.data.loader.DataLoader
  batch_size: 4
  batch_size_factor: 1.0
  cycle: true
  num_batches_per_epoch: 5
  shuffle: true
  num_workers: 0
  collate_fn:
    _target_: uni2ts.data.loader.PackCollate
    max_length: ${model.module_kwargs.max_seq_len}
    seq_fields: ${cls_getattr:${model._target_},seq_fields}
    pad_func_map: ${cls_getattr:${model._target_},pad_func_map}
  pin_memory: true
  drop_last: false
  fill_last: false
  worker_init_fn: null
  prefetch_factor: 2
  persistent_workers: true
val_dataloader:
  _target_: uni2ts.data.loader.DataLoader
  batch_size: 32
  batch_size_factor: 2.0
  cycle: false
  num_batches_per_epoch: null
  shuffle: false
  num_workers: 0
  collate_fn:
    _target_: uni2ts.data.loader.PackCollate
    max_length: ${model.module_kwargs.max_seq_len}
    seq_fields: ${cls_getattr:${model._target_},seq_fields}
    pad_func_map: ${cls_getattr:${model._target_},pad_func_map}
  pin_memory: false
  drop_last: false
  fill_last: true
  worker_init_fn: null
  prefetch_factor: 2
  persistent_workers: true
cuda_device: '0'
